### PR TITLE
Direct conversion from frame data to numpy array

### PR DESCRIPTION
**Pull request by jrast**
I think this would be a useful feature as the frame byte data must be converted to another format in most cases anyways. As numpy is supported by many image processing librarys it would be helpful to have the data available as numpy array without making the roundtrip over getBufferByteData.

Fell free to ignore / extend this pull request.

### CODE REVIEW

**Comment by jayich** [comment]
According to https://github.com/morefigs/pymba/blob/master/setup.py numpy is required for pymba.

Does dtype=unint8 limit the bit depth for cameras that support a 12 bit mode?

**Comment by jrast** [comment]
What do you mean with "numpy is required for pymba"? Do you think it is a good idea to offer a function to convert directly to numpy.ndarray?

You are right, at the moment the implementation only supports 8bit mode. 

How do you currently convert / interpret the 12bit data comming from the ```getBufferByteData``` function? I think it should be possible to integrate this conversion in the ```getImage``` function too.

As you can see I used the frame data and not the camera data (i.e. ```self._frame.imageSize``` vs. ```self.payloadSize```) to decide the size of the image. I think this change should be considered for the ```getBufferByteData``` too because the frame struct contains certainly the correct data as it comes direct from the Vimba API. And the frame struct contains all necessairy data to get the actual image data.

**Comment by jayich** [comment]
Converting to an numpy array directly looks good to me.  I was just affirming that numpy is already required for pymba.

I only work with 8 bit data.  Just looking out for others that might use 12 bit.

**Comment by derricw** [comment]
I work with color and 16-bit images constantly, so if this is merged I may add support for some kind of mapping of the numpy types for color and 16-bit images.  For example using `np.uint16` for `Mono16` images and HxWx3 ndarray shape for color images.

**Comment by jrast** [comment]
What do you think about the change on how the size is determined? Do you think it's better to stick with the old version and get the data from the camera or is it better to get the information from the actual frame?

BTW: I've done a small performance check and the the direct conversion to a numpy array is about 25% faster than the old version. But the conversion is fast in both cases so it's more a memory thing.

**Comment by jayich** [comment]
If I understand correctly the frame is more likely to have the correct image dimensions than the camera.  If this is the case the frame sounds like the way to go.

**Comment by morefigs** [comment]
Thanks. Added a try/except so that numpy is not a hard requirement for pymba (this new method is the only one that actually requires it).

**Pull request merged**
