### PR TITLE
added 32bit-arch detection and 16 bit buffer conversion

### PR DESCRIPTION
**Pull request by rbogle**
These are old changes behind the base master, but may be valuable to issue #15. I can confirm these both work well.

### CODE REVIEW

**Comment by DanielArnett** [comment]
Thanks for adding x86_32bit support. Here the change to vimbadll.py that I made to get arm working as well, feel free to integrate it.


```python
if sys_plat == "win32":
    from ctypes.util import find_msvcrt
    _cruntime = cdll.LoadLibrary(find_msvcrt())
    if '64' in platform.architecture()[0]:
        vimbaC_path = r'C:\Program Files\Allied Vision Technologies\AVTVimba_1.3\VimbaC\Bin\Win64\VimbaC.dll'
    else:
        vimbaC_path = r'C:\Program Files\Allied Vision Technologies\AVTVimba_1.3\VimbaC\Bin\Win32\VimbaC.dll'
    dll_loader = windll
else:
    _cruntime = CDLL("libc.so.6")
    dll_loader = cdll
    if 'x86_64' in os.uname()[4]:
        assert os.environ.get(
            "GENICAM_GENTL64_PATH"), "you need your GENICAM_GENTL64_PATH environment set.  Make sure you have Vimba installed, and you have loaded the /etc/profile.d/ scripts"
        vimba_dir = "/".join(os.environ.get("GENICAM_GENTL64_PATH").split("/")
                             [1:-3])
        vimbaC_path = "/" + vimba_dir + "/VimbaC/DynamicLib/x86_64bit/libVimbaC.so"
    elif 'x86_32' in os.uname()[4]:
        print "Warning: x86_32 reached!"
        assert os.environ.get(
            "GENICAM_GENTL32_PATH"), "you need your GENICAM_GENTL32_PATH environment set.  Make sure you have Vimba installed, and you have loaded the /etc/profile.d/ scripts"
        vimba_dir = "/".join(os.environ.get("GENICAM_GENTL32_PATH").split("/")
                             [1:-3])
        vimbaC_path = "/" + vimba_dir + "/VimbaC/DynamicLib/x86_32bit/libVimbaC.so"
    elif 'arm' in os.uname()[4]:
        assert os.environ.get(
            "GENICAM_GENTL32_PATH"), "you need your GENICAM_GENTL32_PATH environment set.  Make sure you have Vimba installed, and you have loaded the /etc/profile.d/ scripts"
        vimba_dir = "/".join(os.environ.get("GENICAM_GENTL32_PATH").split("/")
                             [1:-3])
        vimbaC_path = "/" + vimba_dir + "/VimbaC/DynamicLib/arm_32bit/libVimbaC.so"
    else:
        print "What the hell kind of futuristic architecture are you using?"

with open(vimbaC_path) as thefile:
    pass # NJO i think this is kind of like an os.exists ?
```

**Comment by morefigs** [comment]
Sorry, this seems to be outdated now. If you rebase/etc I can accept quicker this time.

**Comment by morefigs** [comment]
This is mostly redundant now. If you could add `getBufferIntData` to a new PR then I'll add it. Thanks.

**Comment by morefigs** [comment]
Closing. Please rebase and create a new PR if this is still relevant.

**Pull request closed without merging**
