### PR TITLE
Initial python 3 support

### PR DESCRIPTION
**Pull request by mabl**
This adds basic support for python 3. The main points handled here are
- Absolute imports fixed
- Unicode handling, where I tried to push all encoding into pymba
- VimbaC_MemoryBlock has been rewritten, since python 3.5 has no monolithic C run time anymore.

The code works for my application and should support Python 2 and 3 at the same time.

### CODE REVIEW

**Comment by morefigs** [comment]
Thanks for this. Can you explain more about the VimbaC_MemoryBlock change? Have you tested with Python 2 and 3?

**Comment by mabl** [comment]
> Can you explain more about the VimbaC_MemoryBlock change? 
Sure. Starting with Python 3.5, the Windows version is compiled with Visual Studio 2015, which split up the C runtime into multiple files. You can finde some background [here](http://stevedower.id.au/blog/building-for-python-3-5/). As a side effect ``cdll.LoadLibrary(find_msvcrt())`` cannot work anymore, since there is no single file to look at. Fortunately, we only used the c library to call ``malloc`` to get mutable memory. While looking for a solution, I found that ctypes implements the [``create_string_buffer``](https://docs.python.org/2/library/ctypes.html#ctypes.create_string_buffer) which indeed creates a mutable memory buffer.  ```VimbaC_MemoryBlock``` is hence now only a wrapper around the ctypes memory chunk object.

> Have you tested with Python 2 and 3?
Regarding  Python 2 testing, I've done some, but not so deeply. At least all of my applications worked under both versions. The biggest issue is ``byte`` vs. ``string`` vs ``unicode`` handling. There might still be dragons in there. As for example some of the problems pointed out in #19. I'll have a look at them too.

**Comment by fstarr** [comment]
Hi,

what's the status of this PR? We'd like to use *pymba* in of our own tools that runs under Python 3+ only. We successfully applied this patch in order to make *pymba* Py3-compatible. Rather than maintaining our own *pymba* fork with the needed patches, we'd like to see this patch getting merged into upstream.

Could you share your thoughts on merging this?

Thanks!

**Comment by jtravs** [comment]
I also have been successfully using this branch for python 3 support, and would prefer it "upstreamed". Thanks!

**Comment by morefigs** [comment]
Will have a look soon, it's not allowing an auto merge so I'll have to look into why it's conflicted.

**Comment by fstarr** [comment]
Cool, thank you! 👍 

The merge conflicts were caused by formatting differences iirc. Nothing serious. We were able to figure it out within minutes without knowing the code base.

**Comment by morefigs** [comment]
Accepted, thanks!

**Pull request closed without merging**
